

select * from ZIPCODE5



CREATE TABLE APT_COMPLEX(
   COMPLEX_ID NUMBER PRIMARY KEY,
   COMPLEX_ADDRESS VARCHAR2(300) NOT NULL,
   COMPLEX_LAT NUMBER NOT NULL,
   COMPLEX_LNG NUMBER NOT NULL,
   COMPLEX_APARTNAME VARCHAR2(50) NOT NULL,
   COMPLEX_PDATE DATE NOT NULL,
   COMPLEX_STATE NUMBER NOT NULL,
   COMPLEX_INFO VARCHAR2(1000),
   COMPLEX_SUBWAY NUMBER NOT NULL,
   COMPLEX_STATION VARCHAR2(30),
   COMPLEX_FOOT NUMBER
);





CREATE TABLE APARTMENT(
   APART_ID NUMBER PRIMARY KEY,
   COMPLEX_ID NUMBER REFERENCES APT_COMPLEX(COMPLEX_ID),
   APART_DONG NUMBER NOT NULL,
   APART_HO NUMBER NOT NULL,
   APART_FLOOR NUMBER NOT NULL,
   APART_AREA NUMBER NOT NULL,
   APART_PRICE NUMBER NOT NULL,
   APART_ROOM NUMBER NOT NULL,
   APART_TOILET NUMBER NOT NULL,
   APART_INTERIOR VARCHAR2(1000))
   
   
   
   
   select * from apartment
   
select * from apt_complex







insert into apt_complex 
		values(2,'서울특별시 강남구 개포동',24.5,22.5,'우성아파트',sysdate,1,'좋은아파트 입니다','1','서울역',15)
		insert into apt_complex 
		values(15,'서울특별시 강남구 청담동',24.5,22.5,'우성아파트',sysdate,1,'좋은아파트 입니다','1','서울역',15)




